# -*- coding: utf-8 -*-
"""HR_Attrition_Queries.sql

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7i9IG5llLkK3beNYCyYw41kzpTWI61s
"""

import sqlite3

# Load CSV into SQLite
conn = sqlite3.connect(':memory:')
df.to_sql('hr_data', conn, index=False, if_exists='replace')

# Run a query
query = """
SELECT Department,
       COUNT(*) AS total,
       ROUND(SUM(Attrition_Flag) * 100.0 / COUNT(*), 2) AS attrition_rate
FROM hr_data
GROUP BY Department
ORDER BY attrition_rate DESC
"""
result = pd.read_sql_query(query, conn)
print(result)

# ============================================================
# HR EMPLOYEE ATTRITION — SQL ANALYSIS
# Analyst  : Krati
# Platform : Google Colab (SQLite)
# Run this file SEPARATELY from your Python analysis file
# ============================================================

import pandas as pd
import sqlite3

# -------------------------------------------------------
# STEP 1 — Load CSV and create SQL database
# -------------------------------------------------------
# Upload your CSV in Colab first, then run this
df = pd.read_csv('/content/HR_Employee_Attrition_Dataset.csv')
df['Attrition_Flag'] = df['Attrition'].apply(lambda x: 1 if x == 'Yes' else 0)

conn = sqlite3.connect(':memory:')          # creates database in RAM
df.to_sql('hr_data', conn, index=False, if_exists='replace')

print("✅ Database ready! Total rows:", len(df))

# Helper function — runs any query and shows result neatly
def run_query(title, query):
    print("\n" + "="*55)
    print(f"  {title}")
    print("="*55)
    result = pd.read_sql_query(query, conn)
    print(result.to_string(index=False))
    return result

# -------------------------------------------------------
# QUERY 1 — Overall Attrition Rate
# -------------------------------------------------------
run_query("QUERY 1: Overall Attrition Rate", """
SELECT
    COUNT(*)                                              AS total_employees,
    SUM(Attrition_Flag)                                   AS employees_left,
    ROUND(SUM(Attrition_Flag) * 100.0 / COUNT(*), 2)     AS attrition_rate_pct
FROM hr_data
""")

# -------------------------------------------------------
# QUERY 2 — Department wise Attrition
# -------------------------------------------------------
run_query("QUERY 2: Attrition by Department", """
SELECT
    Department,
    COUNT(*)                                              AS total,
    SUM(Attrition_Flag)                                   AS left_count,
    ROUND(SUM(Attrition_Flag) * 100.0 / COUNT(*), 2)     AS attrition_rate_pct
FROM hr_data
GROUP BY Department
ORDER BY attrition_rate_pct DESC
""")

# -------------------------------------------------------
# QUERY 3 — Salary vs Attrition
# -------------------------------------------------------
run_query("QUERY 3: Avg Salary — Left vs Stayed", """
SELECT
    Attrition,
    ROUND(AVG(MonthlyIncome), 0)    AS avg_salary,
    ROUND(AVG(Age), 1)              AS avg_age,
    ROUND(AVG(YearsAtCompany), 1)   AS avg_tenure
FROM hr_data
GROUP BY Attrition
""")

# -------------------------------------------------------
# QUERY 4 — HIGH RISK Employees (still working, likely to leave)
# -------------------------------------------------------
run_query("QUERY 4: High Risk Employees (Retention Priority)", """
SELECT
    EmployeeID, Department, JobRole,
    MonthlyIncome, JobSatisfaction, OverTime, YearsAtCompany
FROM hr_data
WHERE OverTime       = 'Yes'
  AND MonthlyIncome  < 30000
  AND JobSatisfaction <= 2
  AND Attrition      = 'No'
ORDER BY MonthlyIncome ASC
""")

# -------------------------------------------------------
# QUERY 5 — Overtime Impact
# -------------------------------------------------------
run_query("QUERY 5: Overtime vs Attrition Rate", """
SELECT
    OverTime,
    COUNT(*)                                              AS total,
    SUM(Attrition_Flag)                                   AS left_count,
    ROUND(SUM(Attrition_Flag) * 100.0 / COUNT(*), 2)     AS attrition_rate_pct
FROM hr_data
GROUP BY OverTime
""")

# -------------------------------------------------------
# QUERY 6 — City wise Attrition
# -------------------------------------------------------
run_query("QUERY 6: Attrition by City", """
SELECT
    City,
    COUNT(*)                                              AS total,
    SUM(Attrition_Flag)                                   AS left_count,
    ROUND(SUM(Attrition_Flag) * 100.0 / COUNT(*), 2)     AS attrition_rate_pct
FROM hr_data
GROUP BY City
ORDER BY attrition_rate_pct DESC
""")

# -------------------------------------------------------
# QUERY 7 — Job Satisfaction
# -------------------------------------------------------
run_query("QUERY 7: Job Satisfaction vs Attrition", """
SELECT
    JobSatisfaction,
    COUNT(*)                                              AS total,
    SUM(Attrition_Flag)                                   AS left_count,
    ROUND(SUM(Attrition_Flag) * 100.0 / COUNT(*), 2)     AS attrition_rate_pct
FROM hr_data
GROUP BY JobSatisfaction
ORDER BY JobSatisfaction ASC
""")

# -------------------------------------------------------
# QUERY 8 — Age Group Attrition
# -------------------------------------------------------
run_query("QUERY 8: Age Group Attrition", """
SELECT
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        ELSE '46-60'
    END AS age_group,
    COUNT(*)                                              AS total,
    SUM(Attrition_Flag)                                   AS left_count,
    ROUND(SUM(Attrition_Flag) * 100.0 / COUNT(*), 2)     AS attrition_rate_pct
FROM hr_data
GROUP BY age_group
ORDER BY attrition_rate_pct DESC
""")

print("\n" + "="*55)
print("  ✅ ALL 8 SQL QUERIES COMPLETE — Analyst: Krati")
print("="*55)